// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int more= 0;
		int less= 0;
		for(int i=0; i < N; i++){
			double random = Math.random();
			if(random > 0.5)
				more++;
			else
				less++;
		}
		System.out.println("> 0.5: " + more + " times");
		System.out.println("<= 0.5: " + less + " times");
		if ((more != 0) && (less != 0)) {
			System.out.println((double) more / less);
		}
		
	}
}
